---
- hosts: "{{ bastion_name }}"
  gather_facts: False
  tasks:
    - name: gather ec2 info
      ec2_metadata_facts:

- hosts: "{{ group_name }}"
  roles: 
    - role: block_producer_create_can_snapshot