---
- hosts: "{{ bastion_name }}"
  gather_facts: False
  tasks:
    - name: gather ec2 info
      ec2_metadata_facts:

- hosts: "{{ group_name }}"
  become: yes
  tasks: 
    - name: ping test
      ping: 
