plugin: aws_ec2
regions: 
  - ap-southeast-1
  - ap-southeast-2
  - ap-east-1
  - ap-northeast-1
  - ap-northeast-2
  - ap-south-1
  - me-south-1
  - sa-east-1
  - us-east-1
  - us-east-2
  - us-west-1
  - ca-central-1
  - eu-central-1
  - eu-west-2
  - eu-north-1

strict: False

filters:
  tag:Name: SSH Bastion Host

keyed_groups:
  - key: tags['Name']
    prefix: all
  - key: placement.region
    prefix: bastion

hostnames:
  - ip-address
  - instance-id  # If there's no ip-address value (instance-offline) then show Instance Id
  - tag:Name   # If there's no ip-address value, this attribute will be shown in inventory graph
  - private-ip-address   # If there's no ip-address, tag:Name value, this attribute will be shown in inventory graph
