---
ansible_python_interpreter: /usr/bin/python3
ansible_ssh_private_key_file: /home/ubuntu/.ssh/canchain-admin-kor.pem
ansible_ssh_common_args: -o ProxyCommand="ssh -i /home/ubuntu/.ssh/canchain-admin-kor.pem -W %h:%p ubuntu@{{ hostvars[groups['bastion_ap_northeast_2'][0]]['ansible_ec2_public_ipv4'] }}"
ansible_ssh_user: ubuntu